version: '3'
services:
  docker:
    image: docker:dind
    privileged: true
    restart: always
    volumes:
      - data:/tmp
      - /tmp/docker/containers:/var/lib/docker/containers
      - image:/var/lib/docker
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  api:
    build: master
    restart: always
    ports:
      - 3000:8080
    links:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    env_file: ./master/.env
    volumes:
        - data:/tmp
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  image:
