version: '3'
services:
  docker:
    image: docker:dind
    privileged: true
  api:
    build: master
    ports:
      - 3000:8080
    links:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
