version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
  compiler:
    build: master
    ports:
      - 3000:8080
    links:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375
