version: '3'
services:
  docker:
    image: docker:dind
    privileged: true
    restart: always
    volumes:
      - data:/tmp
      - /tmp/docker/containers:/var/lib/docker/containers
      - image:/var/lib/docker
      - certs-ca:/certs/ca
      - certs-cli:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  api:
    build: master
    restart: always
    ports:
      - 3000:8080
    links:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    env_file: ./master/.env
    volumes:
        - data:/tmp
        - certs-ca:/certs/ca:ro
        - certs-cli:/certs/client:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  image:
  certs-ca:
  certs-cli:
